var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/invoice/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0g8_qsi._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/_0lo8o5g._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/[root-of-the-server]__0xi~igs._.js")
R.c("server/chunks/node_modules_0gnf0qa._.js")
R.c("server/chunks/_next-internal_server_app_api_invoice_[id]_route_actions_0ecyrph.js")
R.m(71865)
module.exports=R.m(71865).exports
