var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/sign-up/[[...sign-up]]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0pne6fn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0g1y8-l._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0nao9fp.js")
R.c("server/chunks/ssr/[root-of-the-server]__0r~_8~c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/app_0h39-ao._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/[root-of-the-server]__08s3in2._.js")
R.c("server/chunks/ssr/node_modules_next_0t~9599._.js")
R.c("server/chunks/ssr/node_modules_@clerk_0rb_1c9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ve2ws3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cvo06_._.js")
R.m(20560)
module.exports=R.m(20560).exports
