// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/buyers" | "/admin/dashboard" | "/admin/inventory" | "/admin/invoices" | "/admin/ledger" | "/admin/orders" | "/admin/products" | "/cart" | "/checkout" | "/contact-us" | "/dashboard" | "/dashboard/orders" | "/dashboard/orders/[id]" | "/onboarding" | "/products" | "/products/[id]" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]"
type AppRouteHandlerRoutes = "/api/categories" | "/api/categories/[id]" | "/api/checkout" | "/api/internal/role" | "/api/inventory/logs" | "/api/inventory/report" | "/api/inventory/update" | "/api/invoice" | "/api/invoice/[id]" | "/api/ledger" | "/api/ledger/[id]" | "/api/orders" | "/api/orders/[id]" | "/api/orders/[id]/invoice" | "/api/payments/razorpay" | "/api/products" | "/api/products/[id]" | "/api/upload" | "/api/users" | "/api/users/[id]" | "/api/users/profile" | "/api/users/role" | "/api/users/sync"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/buyers": {}
  "/admin/dashboard": {}
  "/admin/inventory": {}
  "/admin/invoices": {}
  "/admin/ledger": {}
  "/admin/orders": {}
  "/admin/products": {}
  "/api/categories": {}
  "/api/categories/[id]": { "id": string; }
  "/api/checkout": {}
  "/api/internal/role": {}
  "/api/inventory/logs": {}
  "/api/inventory/report": {}
  "/api/inventory/update": {}
  "/api/invoice": {}
  "/api/invoice/[id]": { "id": string; }
  "/api/ledger": {}
  "/api/ledger/[id]": { "id": string; }
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/orders/[id]/invoice": { "id": string; }
  "/api/payments/razorpay": {}
  "/api/products": {}
  "/api/products/[id]": { "id": string; }
  "/api/upload": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/api/users/profile": {}
  "/api/users/role": {}
  "/api/users/sync": {}
  "/cart": {}
  "/checkout": {}
  "/contact-us": {}
  "/dashboard": {}
  "/dashboard/orders": {}
  "/dashboard/orders/[id]": { "id": string; }
  "/onboarding": {}
  "/products": {}
  "/products/[id]": { "id": string; }
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
