module.exports=[2157,(a,b,c)=>{b.exports=a.x("node:fs",()=>require("node:fs"))},50227,(a,b,c)=>{b.exports=a.x("node:path",()=>require("node:path"))},82943,a=>{"use strict";let b,c;var d=Object.getOwnPropertyNames;let e=(b={"src/runtime/node/safe-node-apis.js"(b,c){let{existsSync:d,writeFileSync:e,readFileSync:f,appendFileSync:g,mkdirSync:h,rmSync:i}=a.r(2157);c.exports={fs:{existsSync:d,writeFileSync:e,readFileSync:f,appendFileSync:g,mkdirSync:h,rmSync:i},path:a.r(50227),cwd:()=>process.cwd()}}},function(){return c||(0,b[d(b)[0]])((c={exports:{}}).exports,c),c.exports})();function f(a,b){if(!a)throw Error(`Clerk: ${b} is missing. This is an internal error. Please contact Clerk's support.`)}a.s(["nodeCwdOrThrow",0,()=>(f(e.cwd,"cwd"),e.cwd),"nodeFsOrThrow",0,()=>(f(e.fs,"fs"),e.fs),"nodePathOrThrow",0,()=>(f(e.path,"path"),e.path)],82943)},37936,(a,b,c)=>{"use strict";Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"registerServerReference",{enumerable:!0,get:function(){return d.registerServerReference}});let d=a.r(11857)},13095,(a,b,c)=>{"use strict";function d(a){for(let b=0;b<a.length;b++){let c=a[b];if("function"!=typeof c)throw Object.defineProperty(Error(`A "use server" file can only export async functions, found ${typeof c}.
Read more: https://nextjs.org/docs/messages/invalid-use-server-value`),"__NEXT_ERROR_CODE",{value:"E352",enumerable:!1,configurable:!0})}}Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"ensureServerEntryExports",{enumerable:!0,get:function(){return d}})},27607,26022,a=>{"use strict";var b=a.i(37936),c=a.i(5246),d=a.i(13095);async function e(){(await (0,c.cookies)()).delete(`__clerk_invalidate_cache_cookie_${Date.now()}`)}(0,d.ensureServerEntryExports)([e]),(0,b.registerServerReference)(e,"00f3e75f489df63e22ef39defe520418791567ad89",null),a.s(["invalidateCacheAction",0,e],27607),a.i(70396);var f=a.i(73727),g=a.i(83693),h=a.i(63365),i=a.i(43197);let j="__clerk_keys_";async function k(a){let b=new TextEncoder().encode(a);return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",b))).map(a=>a.toString(16).padStart(2,"0")).join("").slice(0,16)}async function l(){let a=process.env.PWD;if(!a)return`${j}0`;let b=a.split("/").filter(Boolean).slice(-3).reverse().join("/"),c=await k(b);return`${j}${c}`}async function m(a){let b;if(!i.canUseKeyless)return;let c=await l();try{b=JSON.parse(a(c)||"{}")}catch{b=void 0}return b}var n=a.i(59134);function o(a){return`
\x1b[35m
[Clerk]:\x1b[0m You are running in keyless mode.
You can \x1b[35mclaim your keys\x1b[0m by visiting ${a.claimUrl}
`}let p=function(){if((0,n.t)())return globalThis.__clerk_internal_keyless_logger||(globalThis.__clerk_internal_keyless_logger={__cache:new Map,log:function({cacheKey:a,msg:b}){this.__cache.has(a)&&Date.now()<(this.__cache.get(a)?.expiresAt||0)||(console.log(b),this.__cache.set(a,{expiresAt:Date.now()+6e5}))},run:async function(a,{cacheKey:b,onSuccessStale:c=6e5,onErrorStale:d=6e5}){if(this.__cache.has(b)&&Date.now()<(this.__cache.get(b)?.expiresAt||0))return this.__cache.get(b)?.data;try{let d=await a();return this.__cache.set(b,{expiresAt:Date.now()+c,data:d}),d}catch(a){throw this.__cache.set(b,{expiresAt:Date.now()+d}),a}}}),globalThis.__clerk_internal_keyless_logger}(),q=".clerk";function r(a,b){let c=new Headers;return a&&c.set("Clerk-Framework",a),b&&c.set("Clerk-Framework-Version",b),c}var s=a.i(75582),t=a.i(82943);let u=null;function v(){if(!u){let a,b=(0,s.createClerkClientWithOptions)({});u=function(a){let{storage:b,api:c,framework:d,frameworkVersion:e}=a,f=!1,g=()=>{try{let a=b.read();if(!a)return;return JSON.parse(a)}catch{return}};return{async getOrCreateKeys(){let a=g();if(a?.publishableKey&&a?.secretKey)return a;let f=r(d,e),h=await c.createAccountlessApplication(f);return h&&b.write(JSON.stringify(h)),h},readKeys:()=>g(),removeKeys(){b.remove()},async completeOnboarding(){let a=r(d,e);return c.completeOnboarding(a)},logKeylessMessage(a){f||(f=!0,console.log(`[Clerk]: Running in keyless mode. Claim your keys at: ${a}`))},async resolveKeysWithKeylessFallback(a,b){let c,d,e=a,f=b;try{let b=g();if(a&&a===b?.publishableKey&&b){try{await p?.run(()=>this.completeOnboarding(),{cacheKey:`${b.publishableKey}_complete`,onSuccessStale:864e5})}catch{}return p?.log({cacheKey:`${b.publishableKey}_claimed`,msg:`
\x1b[35m
[Clerk]:\x1b[0m Your application is running with your claimed keys.
You can safely remove the \x1b[35m.clerk/\x1b[0m from your project.
`}),{publishableKey:e,secretKey:f,claimUrl:c,apiKeysUrl:d}}if(!e&&!f){let a=await this.getOrCreateKeys();a&&(e=a.publishableKey,f=a.secretKey,c=a.claimUrl,d=a.apiKeysUrl,p?.log({cacheKey:a.publishableKey,msg:o(a)}))}}catch{}return{publishableKey:e,secretKey:f,claimUrl:c,apiKeysUrl:d}}}}({storage:(a=(0,t.nodeFsOrThrow)(),function(a,b,c={}){let{cwd:d=()=>process.cwd(),frameworkPackageName:e="@clerk/shared"}=c,f=!1,g=()=>b.join(d(),q),h=()=>b.join(g(),".tmp"),i=()=>b.join(h(),"keyless.json"),j=()=>b.join(d(),"clerk.lock"),k=()=>{if(f||a.existsSync(j()))return!1;f=!0;try{return a.writeFileSync(j(),"This file can be deleted if your app is stuck.",{encoding:"utf8",mode:420}),!0}catch{return f=!1,!1}},l=()=>{f=!1;try{a.existsSync(j())&&a.rmSync(j(),{force:!0})}catch{}};return{read(){try{if(!a.existsSync(i()))return"";return a.readFileSync(i(),{encoding:"utf-8"})}catch{return""}},write(c){if(k())try{let f,g,j,k;f=h(),a.existsSync(f)||a.mkdirSync(f,{recursive:!0}),g=b.join(d(),".gitignore"),j=`/${q}/`,a.existsSync(g)||a.writeFileSync(g,"",{encoding:"utf8",mode:420}),a.readFileSync(g,{encoding:"utf-8"}).includes(j)||a.appendFileSync(g,`
# clerk configuration (can include secrets)
${j}
`),k=`## DO NOT COMMIT
This directory is auto-generated from \`${e}\` because you are running in Keyless mode.
Avoid committing the \`.clerk/\` directory as it includes the secret key of the unclaimed instance.
`,a.writeFileSync(b.join(h(),"README.md"),k,{encoding:"utf8",mode:384}),a.writeFileSync(i(),c,{encoding:"utf8",mode:384})}finally{l()}},remove(){if(k())try{a.existsSync(g())&&a.rmSync(g(),{recursive:!0,force:!0})}finally{l()}}}}(a,(0,t.nodePathOrThrow)(),{cwd:(0,t.nodeCwdOrThrow)(),frameworkPackageName:"@clerk/nextjs"})),api:{async createAccountlessApplication(a){try{return await b.__experimental_accountlessApplications.createAccountlessApplication({requestHeaders:a})}catch{return null}},async completeOnboarding(a){try{return await b.__experimental_accountlessApplications.completeAccountlessApplicationOnboarding({requestHeaders:a})}catch{return null}}},framework:"nextjs"})}return u}let w={secure:!1,httpOnly:!1,sameSite:"lax"};async function x(a){let{claimUrl:b,publishableKey:d,secretKey:e,returnUrl:g}=a,i=await (0,c.cookies)(),j=new Request("https://placeholder.com",{headers:await (0,c.headers)()}),k=await m(a=>{var b;return null==(b=i.get(a))?void 0:b.value}),n=(null==k?void 0:k.publishableKey)===d,o=(null==k?void 0:k.secretKey)===e;n&&o||(i.set(await l(),JSON.stringify({claimUrl:b,publishableKey:d,secretKey:e}),w),(0,h.detectClerkMiddleware)(j)&&(0,f.redirect)(`/clerk-sync-keyless?returnUrl=${g}`,f.RedirectType.replace))}async function y(){let a;if(!i.canUseKeyless)return null;try{a=await v().getOrCreateKeys()}catch{a=null}if(!a)return g.errorThrower.throwMissingPublishableKeyError(),null;null==p||p.log({cacheKey:a.publishableKey,msg:o(a)});let{claimUrl:b,publishableKey:d,secretKey:e,apiKeysUrl:f}=a;return(await (0,c.cookies)()).set(await l(),JSON.stringify({claimUrl:b,publishableKey:d,secretKey:e}),w),{claimUrl:b,publishableKey:d,apiKeysUrl:f}}async function z(){if(i.canUseKeyless)try{await v().removeKeys()}catch{}}(0,d.ensureServerEntryExports)([x,y,z]),(0,b.registerServerReference)(x,"40943d948d6b01e0b2a136dec127cfbe10a0205b27",null),(0,b.registerServerReference)(y,"002460adfdaabcf769900735999eb9f0dcbeba1b50",null),(0,b.registerServerReference)(z,"0046fd4a7de97f73333489bab6227c17b81fab85bd",null),a.s(["createOrReadKeylessAction",0,y],26022)},34084,a=>{"use strict";a.s([],96622),a.i(96622);var b=a.i(27607),c=a.i(26022);a.s(["002460adfdaabcf769900735999eb9f0dcbeba1b50",()=>c.createOrReadKeylessAction,"00f3e75f489df63e22ef39defe520418791567ad89",()=>b.invalidateCacheAction],34084)}];

//# sourceMappingURL=%5Broot-of-the-server%5D__03n98qk._.js.map