var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/inventory/report/route.js")
R.c("server/chunks/[root-of-the-server]__0u2bfv~._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/_0lo8o5g._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0k~hr-j.js")
R.c("server/chunks/node_modules_0gnf0qa._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/_next-internal_server_app_api_inventory_report_route_actions_0y-asq1.js")
R.m(19376)
module.exports=R.m(19376).exports
