var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/upload/route.js")
R.c("server/chunks/[root-of-the-server]__0iag4o6._.js")
R.c("server/chunks/node_modules_0gnf0qa._.js")
R.c("server/chunks/_0lo8o5g._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/[root-of-the-server]__04f0o2e._.js")
R.c("server/chunks/node_modules_next_dist_0fs_96g._.js")
R.c("server/chunks/_next-internal_server_app_api_upload_route_actions_11irfhu.js")
R.m(55739)
module.exports=R.m(55739).exports
